CREATE TABLE menu_aplicacao (
    codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    caminho VARCHAR(100) NOT NULL,
    ativo BOOLEAN DEFAULT true
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
